<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Application\ShippingAddressInterface' shared service.

include_once $this->targetDirs[3].'/src/Application/ShippingAddressInterface.php';
include_once $this->targetDirs[3].'/src/Application/ShippingAddress.php';
include_once $this->targetDirs[3].'/src/Domain/ShippingAddress/Repository/ShippingAddressRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Persistence/Doctrine/ShippingAddressRepository.php';

return $this->services['App\\Application\\ShippingAddressInterface'] = new \App\Application\ShippingAddress(($this->privates['App\\Domain\\Client\\Repository\\ClientRepositoryInterface'] ?? $this->load('getClientRepositoryInterfaceService.php')), new \App\Infrastructure\Persistence\Doctrine\ShippingAddressRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'))));
