<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Client\Repository\ClientRepositoryInterface' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Client/Repository/ClientRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Persistence/Doctrine/ClientRepository.php';

return $this->privates['App\\Domain\\Client\\Repository\\ClientRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\ClientRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
