<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.99J51X7' shared service.

return $this->privates['.service_locator.99J51X7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Infrastructure\\Delivery\\Api\\ClientController::client' => ['privates', '.service_locator.zc3_usP', 'get_ServiceLocator_Zc3UsPService.php', true],
    'App\\Infrastructure\\Delivery\\Api\\ShippingAddressController::add' => ['privates', '.service_locator.JZPpmW9', 'get_ServiceLocator_JZPpmW9Service.php', true],
    'App\\Infrastructure\\Delivery\\Api\\ShippingAddressController::update' => ['privates', '.service_locator.JZPpmW9', 'get_ServiceLocator_JZPpmW9Service.php', true],
    'App\\Infrastructure\\Delivery\\Api\\ClientController:client' => ['privates', '.service_locator.zc3_usP', 'get_ServiceLocator_Zc3UsPService.php', true],
    'App\\Infrastructure\\Delivery\\Api\\ShippingAddressController:add' => ['privates', '.service_locator.JZPpmW9', 'get_ServiceLocator_JZPpmW9Service.php', true],
    'App\\Infrastructure\\Delivery\\Api\\ShippingAddressController:update' => ['privates', '.service_locator.JZPpmW9', 'get_ServiceLocator_JZPpmW9Service.php', true],
]);
