<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Application\ClientInterface' shared service.

include_once $this->targetDirs[3].'/src/Application/ClientInterface.php';
include_once $this->targetDirs[3].'/src/Application/Client.php';

return $this->services['App\\Application\\ClientInterface'] = new \App\Application\Client(($this->privates['App\\Domain\\Client\\Repository\\ClientRepositoryInterface'] ?? $this->load('getClientRepositoryInterfaceService.php')));
