<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_yml_metadata_driver' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/SimplifiedYamlDriver.php';

$this->privates['doctrine.orm.default_yml_metadata_driver'] = $instance = new \Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver([($this->targetDirs[3].'/config/doctrine_mapping/Client') => 'App\\Domain\\Client\\Entity', ($this->targetDirs[3].'/config/doctrine_mapping/ShippingAddress') => 'App\\Domain\\ShippingAddress\\Entity']);

$instance->setGlobalBasename('mapping');

return $instance;
