<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Delivery\Api\ShippingAddressController' shared service.

include_once $this->targetDirs[3].'/src/Infrastructure/Delivery/Api/ShippingAddressController.php';

return $this->services['App\\Infrastructure\\Delivery\\Api\\ShippingAddressController'] = new \App\Infrastructure\Delivery\Api\ShippingAddressController();
