<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\ShippingAddress\Repository\ShippingAddressRepositoryInterface' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/ShippingAddress/Repository/ShippingAddressRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Persistence/Doctrine/ShippingAddressRepository.php';

return $this->privates['App\\Domain\\ShippingAddress\\Repository\\ShippingAddressRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\ShippingAddressRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
