<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Application\ShippingAddressInterface' shared service.

include_once $this->targetDirs[3].'/src/Application/ShippingAddressInterface.php';
include_once $this->targetDirs[3].'/src/Application/ShippingAddress.php';

return $this->services['App\\Application\\ShippingAddressInterface'] = new \App\Application\ShippingAddress(($this->privates['App\\Domain\\Client\\Repository\\ClientRepositoryInterface'] ?? $this->load('getClientRepositoryInterfaceService.php')), ($this->privates['App\\Domain\\ShippingAddress\\Repository\\ShippingAddressRepositoryInterface'] ?? $this->load('getShippingAddressRepositoryInterfaceService.php')));
