<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3rwCQB\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3rwCQB/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerB3rwCQB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerB3rwCQB\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerB3rwCQB\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'B3rwCQB',
    'container.build_id' => '7ff20291',
    'container.build_time' => 1572380185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3rwCQB');
