<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container01mPbwK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container01mPbwK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container01mPbwK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container01mPbwK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container01mPbwK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '01mPbwK',
    'container.build_id' => 'b2035408',
    'container.build_time' => 1572381857,
], __DIR__.\DIRECTORY_SEPARATOR.'Container01mPbwK');
